### ISSUE TITLE
NULL value returned for the comment field

### ISSUE THREAD

**Issue by sahusandeep** [hms-dbmi/IRCT#40]
The comment field is stored as a blob in i2b2. Could you change the value of the fourth parameter to 'true' so that it returns value for comment field. With the current code, a NULL value is returned.

https://github.com/hms-dbmi/IRCT/blob/f48e4ecd7d27c7cbbf3595c6c2c6dceabae1fef5/IRCT-RI/src/main/java/edu/harvard/hms/dbmi/bd2k/irct/ri/i2b2/I2B2XMLResourceImplementation.java#L225

**Comment by gaborkorodi-hms** [comment]
This has been changed.
